### ISSUE TITLE
Windows not working

### ISSUE THREAD

**Issue by jeeeem** [numToStr/Navigator.nvim#23]
Need some help in configuring in Windows. Im not sure why its not working when I'm binding it to a keymap. Its working when I execute a command like `Navigateleft`  but when using the keymap, its not doing anything. 

I tried the example config but still not working. Any idea ? or is it just not working with windows OS

**Comment by numToStr** [comment]
Neovim keybindings might be conflicting with your terminal keybindings.

**Comment by jeeeem** [comment]
Already deleted the mappings still not working. for more context Im using lunarvim

```
local keymap_del = vim.keymap.del

keymap_del({"n","t"}, "<C-h>")
keymap_del({"n","t"}, "<C-l>")
keymap_del({"n","t"}, "<C-j>")
keymap_del({"n","t"}, "<C-k>")

vim.keymap.set({'n', 't'}, '<C-h>', '<CMD>NavigatorLeft<CR>')
vim.keymap.set({'n', 't'}, '<C-l>', '<CMD>NavigatorRight<CR>')
vim.keymap.set({'n', 't'}, '<C-k>', '<CMD>NavigatorUp<CR>')
vim.keymap.set({'n', 't'}, '<C-j>', '<CMD>NavigatorDown<CR>')
```

Additional issue:
It kinda works but it is slow, its not working when I use the `CTRL` for both config, so I just use `CTRL|ALT` in wezterm. 
When I navigate from neovim to wezterm pane, this happened.

![image](https://user-images.githubusercontent.com/51053482/209707758-6f580701-d024-4250-bc4d-d0846c6ded0b.png)

The neovim session suspends when I type `ctrl-c` , i use it for `escape` alternative when going normal mode as I am used using the keybind.

Not sure what I miss, maybe this is not working for windows OS users although I have a workaround (use separate keybindings) but I wanna try if it is possible to navigate more smoothly with this plugin.

**Comment by numToStr** [comment]
I don't think there is any fundamental issue with the plugin itself and I can't help much as I don't use wezterm myself. Though there is already an upstream issue with WezTerm which you can look.

- #20

**Comment by numToStr** [comment]
Closing this for now as this is not related to the plugin.
