### ISSUE TITLE
error on navigating to splits

### ISSUE THREAD

**Issue by lalitmee** [numToStr/Navigator.nvim#6]
Getting this error in the command line every time when I switch between splits.

![image](https://user-images.githubusercontent.com/10762218/134859996-319fe69c-e021-4abb-894c-25a9530fc845.png)

Please help

**Comment by numToStr** [comment]
Did you call `setup()`?

**Comment by lalitmee** [comment]
Oh sorry, actually I was calling `setup()` with `config` and when I tried simple `setup()` it worked. Thanks for pointing it out.
